---
- name: Update Hosts
  hosts: all
  become: true

  vars_files:
    - "vars/sudo_pwd.yaml"      

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_facts["os_family"] == "Debian"

    - name: Upgrade packages
      apt:
        upgrade: full
      when: ansible_facts["os_family"] == "Debian"

    - name: Update dnf packages
      dnf:
        name: "*"
        state: latest
      when: ansible_facts["os_family"] == "RedHat"
