---
- name: My First Playbook
  hosts: all

  vars_files:
    - "vars/sudo_pwd.yaml"

  tasks:
    - name: Write a file
      file:
        state: touch
        path: "/tmp/i_was_here"

    - name: Install htop on Debian devices
      apt:
        name: htop
        state: latest
      become: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Install cmatrix
      apt:
        name: cmatrix
        state: latest
      become: true
      when: ansible_facts['os_family'] == "Debian"
